import { _ } from '../helper.js'

export default {
  shareText: _('推荐 AI Agent面板 — 基于 AI Agent 的可视化管理界面，便捷管理模型与 Agent，内置 AI 助手排障。GitHub：https://github.com/agentai2026/AI-Agent  本地说明：http://localhost:3456/#/website', 'Try AI Agent Panel — an AI Agent-based desktop UI to manage models and Agents, with a built-in assistant for troubleshooting. GitHub: https://github.com/agentai2026/AI-Agent  Local docs: http://localhost:3456/#/website', '推薦 AI Agent面板 — 基於 AI Agent 的可視化管理介面，便捷管理模型與 Agent，內建 AI 助手排障。GitHub：https://github.com/agentai2026/AI-Agent  本地說明：http://localhost:3456/#/website', 'AI Agent Panel（AI Agent ベース）をおすすめします。モデルと Agent を管理し、トラブル用 AI アシスタント付き。GitHub: https://github.com/agentai2026/AI-Agent  ローカル: http://localhost:3456/#/website', 'AI Agent Panel — AI Agent 기반 데스크톱 UI로 모델과 Agent를 관리하고 내장 AI 도우미로 문제를 해결하세요. GitHub: https://github.com/agentai2026/AI-Agent  로컬: http://localhost:3456/#/website', 'Giới thiệu AI Agent Panel — giao diện quản lý AI Agent, tiện quản lý model và Agent, có trợ lý AI xử lý sự cố. GitHub: https://github.com/agentai2026/AI-Agent  Cục bộ: http://localhost:3456/#/website', 'Prueba AI Agent Panel — interfaz AI Agent para gestionar modelos y Agents, con asistente de IA. GitHub: https://github.com/agentai2026/AI-Agent  Local: http://localhost:3456/#/website', 'Experimente o AI Agent Panel — UI AI Agent para gerenciar modelos e Agents, com assistente de IA. GitHub: https://github.com/agentai2026/AI-Agent  Local: http://localhost:3456/#/website', 'Попробуйте AI Agent Panel — интерфейс на базе AI Agent для моделей и агентов, с ИИ-помощником. GitHub: https://github.com/agentai2026/AI-Agent  Локально: http://localhost:3456/#/website', 'Essayez AI Agent Panel — interface AI Agent pour modèles et Agents, avec assistant IA. GitHub : https://github.com/agentai2026/AI-Agent  Local : http://localhost:3456/#/website', 'Empfehlung: AI Agent Panel — AI Agent-basierte Oberfläche für Modelle und Agents, mit KI-Assistent. GitHub: https://github.com/agentai2026/AI-Agent  Lokal: http://localhost:3456/#/website'),
  title: _('感谢你使用 AI Agent面板', 'Thanks for using AI Agent面板', '感謝你使用 AI Agent面板', 'AI Agent面板 を使っていただきありがとうございます', 'AI Agent面板을 사용해 주셔서 감사합니다', 'Cảm ơn bạn đã sử dụng AI Agent面板', 'Gracias por usar AI Agent面板', 'Obrigado por usar o AI Agent面板', 'Спасибо, что используете AI Agent面板', 'Merci d’utiliser AI Agent面板', 'Danke, dass du AI Agent面板 nutzt'),
  message: _('AI Agent面板 是一个<strong>完全开源、免费</strong>的项目，由社区贡献与维护。如果它帮到了你，对我们最大的鼓励就是：', 'AI Agent Panel is a <strong>fully open-source and free</strong> project, maintained by the community. If it helped you, the best encouragement for us is:', 'AI Agent面板 是一個<strong>完全開源、免費</strong>的專案，由社群貢獻與維護。如果它幫到了你，對我們最大的鼓勵就是：', 'AI Agent面板 / AI Agent Panel は<strong>完全オープンソースで無料</strong>のプロジェクトで、コミュニティによって保守されています。役に立ったなら、一番の励みは次のとおりです：', 'AI Agent面板 / AI Agent Panel은 <strong>완전 오픈소스이자 무료</strong> 프로젝트이며 커뮤니티가 유지합니다. 도움이 되었다면 가장 큰 응원은:', 'AI Agent面板 / AI Agent Panel là dự án <strong>mã nguồn mở hoàn toàn và miễn phí</strong>, được cộng đồng duy trì. Nếu hữu ích, sự ủng hộ lớn nhất là:', 'AI Agent面板 / AI Agent Panel es un proyecto <strong>totalmente open source y gratuito</strong>, mantenido por la comunidad. Si te ayudó, lo mejor es:', 'AI Agent面板 / AI Agent Panel é um projeto <strong>totalmente open source e gratuito</strong>, mantido pela comunidade. Se ajudou, o melhor incentivo é:', 'AI Agent面板 / AI Agent Panel — <strong>полностью open-source и бесплатный</strong> проект с поддержкой сообщества. Если помогло, лучшая поддержка для нас:', 'AI Agent面板 / AI Agent Panel est un projet <strong>entièrement open source et gratuit</strong>, maintenu par la communauté. Si cela vous a aidé, le meilleur soutien est :', 'AI Agent面板 / AI Agent Panel ist ein <strong>vollständig quelloffenes und kostenloses</strong> Projekt der Community. Wenn es geholfen hat, ist die beste Unterstützung:'),
  starTitle: _('GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star'),
  starDesc: _('点个 Star 是最直接的支持', 'Giving us a Star is the most direct support', '點個 Star 是最直接的支持', 'Star を付けてもらえるのが一番直接的な応援です', 'Star를 눌러 주는 것이 가장 직접적인 응원입니다', 'Tặng một Star là cách ủng hộ trực tiếp nhất', 'Dar una Star es la forma más directa de apoyarnos', 'Dar uma Star é a forma mais direta de apoiar', 'Поставить Star — самый прямой способ поддержки', 'Mettre une Star est le soutien le plus direct', 'Ein Star ist die direkteste Unterstützung'),
  shareTitle: _('分享给朋友', 'Share with friends', '分享給朋友', '友だちに共有', '친구에게 공유', 'Chia sẻ với bạn bè', 'Compartir con amigos', 'Compartilhar com amigos', 'Поделиться с друзьями', 'Partager avec des amis', 'Mit Freunden teilen'),
  shareDesc: _('复制推荐文案，让更多人知道', 'Copy the recommendation text to spread the word', '複製推薦文案，讓更多人知道', '紹介文をコピーして、もっと多くの人に広めましょう', '추천 문구를 복사해 더 많은 사람에게 알려 주세요', 'Sao chép lời giới thiệu để nhiều người biết hơn', 'Copia el texto de recomendación para que más gente lo conozca', 'Copie o texto de recomendação para divulgar para mais pessoas', 'Скопируйте текст рекомендации, чтобы рассказать другим', 'Copiez le texte de recommandation pour le partager autour de vous', 'Kopiere den Empfehlungstext, damit mehr Leute davon erfahren'),
  shareCopied: _('✅ 已复制，去分享吧！', '✅ Copied, go share it!', '✅ 已複製，去分享吧！', '✅ コピーしました。ぜひ共有してください！', '✅ 복사되었습니다. 이제 공유해 보세요!', '✅ Đã sao chép, hãy chia sẻ ngay!', '✅ ¡Copiado! ¡Ahora compártelo!', '✅ Copiado! Agora compartilhe!', '✅ Скопировано, поделитесь этим!', '✅ Copié, allez le partager !', '✅ Kopiert, jetzt teile es!'),
  communityLabel: _('扫码加入社区交流群，第一时间获取更新和帮助', 'Scan to join the community groups for updates and help', '掃碼加入社群交流群，第一時間獲取更新和幫助', 'QR をスキャンしてコミュニティに参加し、最新情報やサポートを受け取りましょう', 'QR 코드를 스캔해 커뮤니티 그룹에 참여하고 업데이트와 도움을 받아보세요', 'Quét mã để tham gia cộng đồng, nhận cập nhật và hỗ trợ sớm nhất', 'Escanea para unirte a la comunidad y recibir novedades y ayuda', 'Escaneie para entrar na comunidade e receber atualizações e ajuda', 'Сканируйте код, чтобы присоединиться к сообществу и получать новости и помощь', 'Scannez pour rejoindre la communauté et recevoir des mises à jour et de l’aide', 'Scanne den Code, um der Community beizutreten und Updates sowie Hilfe zu erhalten'),
  qqAlt: _('QQ 交流群', 'QQ community group', 'QQ 交流群', 'QQ コミュニティグループ', 'QQ 커뮤니티 그룹', 'Nhóm cộng đồng QQ', 'Grupo de comunidad QQ', 'Grupo da comunidade QQ', 'Сообщество QQ', 'Groupe communautaire QQ', 'QQ-Community-Gruppe'),
  qqLabel: _('QQ 群', 'QQ Group', 'QQ 群', 'QQ グループ', 'QQ 그룹', 'Nhóm QQ', 'Grupo de QQ', 'Grupo QQ', 'Группа QQ', 'Groupe QQ', 'QQ-Gruppe'),
  wechatAlt: _('微信交流群', 'WeChat community group', '微信交流群', 'WeChat コミュニティグループ', '위챗 커뮤니티 그룹', 'Nhóm cộng đồng WeChat', 'Grupo de comunidad WeChat', 'Grupo da comunidade WeChat', 'Сообщество WeChat', 'Groupe communautaire WeChat', 'WeChat-Community-Gruppe'),
  wechatLabel: _('微信群', 'WeChat Group', '微信群', 'WeChat グループ', '위챗 그룹', 'Nhóm WeChat', 'Grupo de WeChat', 'Grupo WeChat', 'Группа WeChat', 'Groupe WeChat', 'WeChat-Gruppe'),
  douyinAlt: _('抖音交流群', 'Douyin community group', '抖音交流群', 'Douyin コミュニティグループ', '도우인 커뮤니티 그룹', 'Nhóm cộng đồng Douyin', 'Grupo de comunidad Douyin', 'Grupo da comunidade Douyin', 'Сообщество Douyin', 'Groupe communautaire Douyin', 'Douyin-Community-Gruppe'),
  douyinLabel: _('抖音群', 'Douyin Group', '抖音群', 'Douyin グループ', '도우인 그룹', 'Nhóm Douyin', 'Grupo de Douyin', 'Grupo Douyin', 'Группа Douyin', 'Groupe Douyin', 'Douyin-Gruppe'),
  feishuAlt: _('飞书交流群', 'Feishu community group', '飛書交流群', 'Feishu コミュニティグループ', '피슈 커뮤니티 그룹', 'Nhóm cộng đồng Feishu', 'Grupo de comunidad Feishu', 'Grupo da comunidade Feishu', 'Сообщество Feishu', 'Groupe communautaire Feishu', 'Feishu-Community-Gruppe'),
  feishuLabel: _('飞书群', 'Feishu Group', '飛書群', 'Feishu グループ', '피슈 그룹', 'Nhóm Feishu', 'Grupo de Feishu', 'Grupo Feishu', 'Группа Feishu', 'Groupe Feishu', 'Feishu-Gruppe'),
  dismissToday: _('今日不再弹窗', 'Do not show again today', '今日不再彈窗', '今日はもう表示しない', '오늘은 다시 보지 않기', 'Hôm nay không hiển thị lại', 'No volver a mostrar hoy', 'Não mostrar novamente hoje', 'Не показывать снова сегодня', 'Ne plus afficher aujourd’hui', 'Heute nicht mehr anzeigen'),
}
